//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagementSystemValueCreed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class approver
    {
        public int ID { get; set; }
        [DisplayName("Employee ID")]
        public string Emplyoee_id { get; set; }
        [DisplayName("Approver ID ")]
        public string approver_id { get; set; }
        [DisplayName("Sequence")]
        public string sequence { get; set; }
        [DisplayName("Employee Name")]
        public string Employee_name { get; set; }
        [DisplayName("Approver Name")]
        public string Approver_name { get; set; }
        [DisplayName("Employee's Department")]
        public string department { get; set; }
    
        public virtual UsersTable UsersTable { get; set; }
        public virtual UsersTable UsersTable1 { get; set; }
    }
}
