//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagementSystemValueCreed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class approval
    {
        public int ID { get; set; }
        public string Employee_id { get; set; }
        public string Aprrover_id { get; set; }
        public string status { get; set; }
        public Nullable<int> Leave_id { get; set; }
    
        public virtual UsersTable UsersTable { get; set; }
        public virtual UsersTable UsersTable1 { get; set; }
    }
}
