//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagementSystemValueCreed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Leave
    {
        public int ID { get; set; }
        [DisplayName("Employee ID")]
        public string Employee_Id { get; set; }
        [RegularExpression(@"^([A-Za-z]+ )+[A-Za-z]+$|^[A-Za-z]+$$", ErrorMessage = "Use letters only please and only one Space allowed")]
        public string Reason { get; set; }
        [DisplayName("Number of Days ")]
        public int Number_of_Days { get; set; }
        [DisplayName("Start Date ")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime Start_Date { get; set; }
        [DisplayName("End Date ")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public System.DateTime End_Date { get; set; }
        [DisplayName("Employee Name ")]
        public string Employe_name { get; set; }
        public string Status { get; set; }
        [DisplayName("Leave Type ")]
        public string LeaveType { get; set; }
        public string Description { get; set; }
        [DisplayName("Leave Apply Date ")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Leave_apply_date { get; set; }
        public Nullable<int> Leave_credit { get; set; }
        public Nullable<int> Leave_debit { get; set; }
        public Nullable<int> Leave_balance { get; set; }
    
        public virtual UsersTable UsersTable { get; set; }
    }
}
