//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveManagementSystemValueCreed.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UsersTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersTable()
        {
            this.approvals = new HashSet<approval>();
            this.approvals1 = new HashSet<approval>();
            this.approvers = new HashSet<approver>();
            this.approvers1 = new HashSet<approver>();
            this.Leaves = new HashSet<Leave>();
        }

        [DisplayName("First Name")]
        [Required(ErrorMessage = "This field is Required")]
        [RegularExpression(@"^([A-Za-z]+ )+[A-Za-z]+$|^[A-Za-z]+$$", ErrorMessage = "Use letters only please and only one Space allowed")]
        public string FIRST_NAME { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "This field is Required")]
        public string LAST_NAME { get; set; }
        [DisplayName("Employee ID")]
        [Required(ErrorMessage = "This field is Required")]
        public string EMPLOYEE_ID { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "This field is Required")]
        public string EMAIL { get; set; }
        [DisplayName("Phone")]
        [Required(ErrorMessage = "This field is Required")]
        public string PHONE { get; set; }
        [DisplayName("Address")]
     
        public string ADDRESS { get; set; }
        public string ALTERNATE_PHONE { get; set; }
        [DisplayName("Emergency Number")]

        public string EMERGENCY_NUMBER { get; set; }
        [DisplayName("Location")]
        [Required(ErrorMessage = "This field is Required")]
        public string LOCATION { get; set; }
        public byte[] PROFILE_PICTURE { get; set; }
        [DisplayName("Blood Group")]

        public string BLOOD_GROUP { get; set; }
        [DisplayName("Designation")]
       
        public string DESCRIPTION { get; set; }
        [DisplayName("Gender")]

        public string GENDER { get; set; }
        [DisplayName("Joining Date")]
        [Required(ErrorMessage = "This field is Required")]
        public System.DateTime Emp_start_date { get; set; }
        [DisplayName("Leaving Date")]
  
        public Nullable<System.DateTime> Emp_end_date { get; set; }
        public string manager_id { get; set; }
        public string Status { get; set; }
        [DisplayName("Role")]
        [Required(ErrorMessage = "This field is Required")]
        public string ROLES { get; set; }
        [DisplayName("Department")]
        [Required(ErrorMessage = "This field is Required")]
        public string DEPARTMENT { get; set; }
        public string manager_name { get; set; }
        [DisplayName("Leave Balance")]
        [Required(ErrorMessage = "This field is Required")]
        public Nullable<int> leaves_alloted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<approval> approvals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<approval> approvals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<approver> approvers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<approver> approvers1 { get; set; }
        public virtual department_tbl department_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave> Leaves { get; set; }
        public virtual RolesTable RolesTable { get; set; }
    }
}
